name: Deploy Functions (Flex)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 (build any local steps if you have)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # If you need npm install/build for your website assets, do it here
      # - run: npm ci && npm run build

      - name: Create deploy zip (repo root)
        run: |
          zip -r deploy.zip . -x ".git/*" ".github/*" ".DS_Store"

      - name: Deploy to Function App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: mystro-sec-endpoint
          package: deploy.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_MYSTRO_SEC_ENDPOINT }}
