# .github/workflows/main_mystro-sec-endpoint.yml
name: Build and deploy Node.js project to Azure Function App - mystro-sec-endpoint

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # <-- IMPORTANT: your Functions project lives in /api
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'api'
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install & build (Functions /api)
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          npm install --no-audit --no-fund
          npm run build --if-present

      - name: Create deployment zip (Functions /api)
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-zip
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-zip

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_34D196C7A11E44F3A5C09A9E07C8E126 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D60273CC69E640BE8D72999E981EE478 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1411B92208BB42328EE01ED189AF5F51 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: mystro-sec-endpoint
          slot-name: Production
          package: release.zip

