name: Deploy Functions (Flex)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: if you build assets, do it here
      # - run: npm ci && npm run build

      - name: Sanity: list function folders at repo root
        run: |
          echo "Expecting: host.json and folders get/ list/ index/ (graph-hook/ ping/ optional)"
          ls -1d host.json get list index graph-hook ping 2>/dev/null || true

      - name: Create deploy zip (repo root)
        run: |
          zip -r deploy.zip . -x ".git/*" ".github/*" ".DS_Store" "deploy.zip"

      - name: Deploy to Function App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: mystro-sec-endpoint
          package: deploy.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_MYSTRO_SEC_ENDPOINT }}

      # Force trigger registration on Flex
      - name: Sync function triggers (host API)
        run: |
          curl -s -f -X POST \
            "https://mystro-sec-endpoint-bjecbgefdbgmhbdv.australiaeast-01.azurewebsites.net/admin/host/synctriggers?code=${{ secrets.FUNCAPP_HOST_KEY }}" \
            -H "Content-Type: application/json"

      - name: Warm ping (optional)
        run: |
          curl -s -I https://mystro-sec-endpoint-bjecbgefdbgmhbdv.australiaeast-01.azurewebsites.net/ || true
