name: Deploy static site to Azure Storage

on:
  push:
    branches: [ main ]
    paths:
      - 'index/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload to $web
        uses: azure/cli@v2
        with:
          inlineScript: |
            # Upload all files from /index into the $web container
            az storage blob upload-batch \
              --account-name mystroblobstore \
              --account-key  ${{ secrets.AZURE_STORAGE_KEY }} \
              --destination '$web' \
              --source index \
              --no-progress

            # Set cache-control so HTML/JS update immediately
            az storage blob update \
              --account-name mystroblobstore \
              --account-key  ${{ secrets.AZURE_STORAGE_KEY }} \
              --container-name '$web' --name index.html \
              --content-cache-control "no-store, no-cache, must-revalidate" || true

            az storage blob update \
              --account-name mystroblobstore \
              --account-key  ${{ secrets.AZURE_STORAGE_KEY }} \
              --container-name '$web' --name script.js \
              --content-cache-control "no-store, no-cache, must-revalidate" || true
